// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eawzznzovrgfxdbcdwzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhd3p6bnpvdnJnZnhkYmNkd3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzIzNjksImV4cCI6MjA1OTk0ODM2OX0.T5LFZfpEROIdInGASQinJWhBW9kMw9N9Aad5BYqQ4mo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);